# Ex 1

In [1]:
import torch
import torch.nn as nn

class Softmax(nn.Module):
    def __init__(self):
        super(Softmax, self).__init__()
        
    def forward(self, x):
        exp_x = torch.exp(x)
        return exp_x / torch.sum(exp_x, dim=0)

class SoftmaxStable(nn.Module):
    def __init__(self):
        super(SoftmaxStable, self).__init__()
        
    def forward(self, x):
        c = torch.max(x)
        exp_x = torch.exp(x - c)
        return exp_x / torch.sum(exp_x, dim=0)

# Examples
data = torch.Tensor([1, 2, 3])
softmax = Softmax()
output = softmax(data)
print(output)
# >> tensor([0.0900, 0.2447, 0.6652])

softmax_stable = SoftmaxStable()
output_stable = softmax_stable(data)
print(output_stable)
# >> tensor([0.0900, 0.2447, 0.6652])


tensor([0.0900, 0.2447, 0.6652])
tensor([0.0900, 0.2447, 0.6652])


# Ex 2

In [2]:
class Person:
    def __init__(self, name, yob):
        self.name = name
        self.yob = yob

    def describe(self):
        return f"Name: {self.name}, YoB: {self.yob}"

class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self.grade = grade

    def describe(self):
        return f"Student - {super().describe()} - Grade: {self.grade}"

class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name, yob)
        self.specialist = specialist

    def describe(self):
        return f"Doctor - {super().describe()} - Specialist: {self.specialist}"

class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self.subject = subject

    def describe(self):
        return f"Teacher - {super().describe()} - Subject: {self.subject}"


In [15]:
class Ward:
    def __init__(self, name):
        self.name = name
        self.people = []

    def add_person(self, person):
        self.people.append(person)

    def describe(self):
        return f"Ward Name: {self.name}\n" + "\n".join([person.describe() for person in self.people])

    def count_doctors(self):
        return sum(1 for person in self.people if isinstance(person, Doctor))

    def sort_age(self):
        self.people.sort(key=lambda person: person.yob)

    def compute_average(self):
        teachers = [person for person in self.people if isinstance(person, Teacher)]
        if not teachers:
            return 0
        return sum(teacher.yob for teacher in teachers) / len(teachers)


## 2(a)

In [16]:
student1 = Student(name="studentA", yob=2010, grade="7")
print(student1.describe())

teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
print(teacher1.describe())

doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
print(doctor1.describe())

Student - Name: studentA, YoB: 2010 - Grade: 7
Teacher - Name: teacherA, YoB: 1969 - Subject: Math
Doctor - Name: doctorA, YoB: 1945 - Specialist: Endocrinologists


## 2(b)

In [17]:
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")
ward1 = Ward(name="Ward1")

ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)

print(ward1.describe())

Ward Name: Ward1
Student - Name: studentA, YoB: 2010 - Grade: 7
Teacher - Name: teacherA, YoB: 1969 - Subject: Math
Teacher - Name: teacherB, YoB: 1995 - Subject: History
Doctor - Name: doctorA, YoB: 1945 - Specialist: Endocrinologists
Doctor - Name: doctorB, YoB: 1975 - Specialist: Cardiologists


## 2(c)

In [18]:
print("Number of Doctors:", ward1.count_doctors())

Number of Doctors: 2


## 2(d)

In [19]:
print("\nAfter sorting Age of Ward1 people")
ward1.sort_age()
print(ward1.describe())


After sorting Age of Ward1 people
Ward Name: Ward1
Doctor - Name: doctorA, YoB: 1945 - Specialist: Endocrinologists
Teacher - Name: teacherA, YoB: 1969 - Subject: Math
Doctor - Name: doctorB, YoB: 1975 - Specialist: Cardiologists
Teacher - Name: teacherB, YoB: 1995 - Subject: History
Student - Name: studentA, YoB: 2010 - Grade: 7


## 2(e)

In [20]:
print(f"\nAverage year of birth (teachers): {ward1.compute_average()}")


Average year of birth (teachers): 1982.0


# Ex 3

In [25]:
class Stack:
    def __init__(self, capacity):
        self.capacity = capacity
        self.elements = []
    
    def is_empty(self):
        return len(self.elements) == 0
    
    def is_full(self):
        return len(self.elements) == self.capacity
    
    def pop(self):
        if self.is_empty():
            raise IndexError("pop from empty stack")
        return self.elements.pop()
    
    def push(self, value):
        if self.is_full():
            raise OverflowError("push to full stack")
        self.elements.append(value)
    
    def top(self):
        if self.is_empty():
            raise IndexError("top from empty stack")
        return self.elements[-1]


In [28]:
stack1 = Stack(capacity=5)

stack1.push(1)
stack1.push(2)

print(stack1.is_full())
print(stack1.top())
print(stack1.pop())
print(stack1.top())
print(stack1.pop())
print(stack1.is_empty())


False
2
2
1
1
True


# Ex 4

In [29]:
class Queue:
    def __init__(self, capacity):
        self.capacity = capacity
        self.elements = []
    
    def is_empty(self):
        return len(self.elements) == 0
    
    def is_full(self):
        return len(self.elements) == self.capacity
    
    def dequeue(self):
        if self.is_empty():
            raise IndexError("dequeue from empty queue")
        return self.elements.pop(0)
    
    def enqueue(self, value):
        if self.is_full():
            raise OverflowError("enqueue to full queue")
        self.elements.append(value)
    
    def front(self):
        if self.is_empty():
            raise IndexError("front from empty queue")
        return self.elements[0]


In [32]:
queue1 = Queue(capacity=5)

queue1.enqueue(1)
queue1.enqueue(2)

print(queue1.is_full())
print(queue1.front())
print(queue1.dequeue())
print(queue1.front())
print(queue1.dequeue())
print(queue1.is_empty())

False
1
1
2
2
True
