In [111]:
import numpy as np

In [112]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################
    w1, w2 = W
    dW1 = 0.2 * w1
    dW2 = 4 * w2

    dW = np.array([dW1, dW2])
    ########################################################

    return dW

In [113]:
def sgd_momentum(W, dW, lr, V, beta):
    """
    Thực hiện thuật tóan Gradient Descent + Momentum để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    V -- np.array: [v1, v2] Exponentially weighted averages gradients
    beta -- float: hệ số long-range average
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    V -- np.array: [v1, v2] Exponentially weighted averages gradients sau khi đã cập nhật
    """
    #################### YOUR CODE HERE ####################

    V = beta * V + (1 - beta) * dW
    W = W - lr * V
    ########################################################
    return W

In [114]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    beta = 0.9
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, v1, v2
    # append cặp [w1, w2] vào list results
    for i in range(epochs):
        dW = df_w(W)
        W = optimizer(W, dW, lr, V, beta)
        results.append(W)

    ########################################################
    return results

In [115]:
train_p1(sgd_momentum, lr=0.6, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.94, -1.52]),
 array([-4.88072, -1.1552 ]),
 array([-4.82215136, -0.877952  ]),
 array([-4.76428554, -0.66724352]),
 array([-4.70711412, -0.50710508]),
 array([-4.65062875, -0.38539986]),
 array([-4.5948212 , -0.29290389]),
 array([-4.53968335, -0.22260696]),
 array([-4.48520715, -0.16918129]),
 array([-4.43138466, -0.12857778]),
 array([-4.37820805, -0.09771911]),
 array([-4.32566955, -0.07426652]),
 array([-4.27376152, -0.05644256]),
 array([-4.22247638, -0.04289634]),
 array([-4.17180666, -0.03260122]),
 array([-4.12174498, -0.02477693]),
 array([-4.07228404, -0.01883047]),
 array([-4.02341663, -0.01431115]),
 array([-3.97513563, -0.01087648]),
 array([-3.92743401, -0.00826612]),
 array([-3.8803048 , -0.00628225]),
 array([-3.83374114, -0.00477451]),
 array([-3.78773625e+00, -3.62862943e-03]),
 array([-3.74228341e+00, -2.75775836e-03]),
 array([-3.69737601e+00, -2.09589636e-03]),
 array([-3.65300750e+00, -1.59288123e-03]),
 array([-3.6091